### ISSUE TITLE
Implementation in viewPager 

### ISSUE THREAD

**Issue by idrisbohra** [whataa/SuitLines#28]
Hi @whataa i try to implement the Suitlines in viewPager Adapter which extends PagerAdapter, but it is keep giving me this error:

Caused by: android.view.InflateException: Binary XML file line #0: Error inflating class <unknown>

Caused by: java.lang.reflect.InvocationTargetException

04-08 15:06:22.370 15856-15856/com.xyz W/System.err:     at java.lang.reflect.Constructor.newInstance0(Native Method)

04-08 15:06:22.370 15856-15856/com.xyz W/System.err:     at java.lang.reflect.Constructor.newInstance(Constructor.java:430)

04-08 15:06:22.370 15856-15856/com.xyz W/System.err:     at android.view.LayoutInflater.createView(LayoutInflater.java:652)

04-08 15:06:22.370 15856-15856/com.xyz W/System.err:     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:794)

04-08 15:06:22.370 15856-15856/com.xyz W/System.err:     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:734)

04-08 15:06:22.371 15856-15856/com.xyz W/System.err:     at android.view.LayoutInflater.rInflate(LayoutInflater.java:865)

04-08 15:06:22.371 15856-15856/com.xyz W/System.err:     at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:828)

04-08 15:06:22.371 15856-15856/com.xyz W/System.err:     at android.view.LayoutInflater.inflate(LayoutInflater.java:525)

04-08 15:06:22.371 15856-15856/com.xyz W/System.err:     at android.view.LayoutInflater.inflate(LayoutInflater.java:427)

04-08 15:06:22.371 15856-15856/com.xyz W/System.err:     at com.tentwenty.notifyme.adapter.HomeGraphSlideAdapter.instantiateItem(HomeGraphSlideAdapter.java:57)

04-08 15:06:22.371 15856-15856/com.xyz W/System.err:     at com.tentwenty.notifyme.adapter.HomeGraphSlideAdapter.instantiateItem(HomeGraphSlideAdapter.java:34)

04-08 15:06:22.371 15856-15856/com.xyz W/System.err:     at android.support.v4.view.ViewPager.addNewItem(ViewPager.java:1002)

04-08 15:06:22.371 15856-15856/com.xyz W/System.err:     at android.support.v4.view.ViewPager.populate(ViewPager.java:1150)

04-08 15:06:22.371 15856-15856/com.xyz W/System.err:     at android.support.v4.view.ViewPager.populate(ViewPager.java:1084)

04-08 15:06:22.371 15856-15856/com.xyz W/System.err:     at android.support.v4.view.ViewPager.setAdapter(ViewPager.java:534)

04-08 15:06:22.371 15856-15856/com.xyz W/System.err:     at com.tentwenty.notifyme.activity.HomeGraphDetailActivity$GetGraphDataNetworkThread$1.onSuccess(HomeGraphDetailActivity.java:389)

04-08 15:06:22.371 15856-15856/com.xyz W/System.err:     at com.loopj.android.http.JsonHttpResponseHandler$1$1.run(JsonHttpResponseHandler.java:152)

04-08 15:06:22.371 15856-15856/com.xyz W/System.err:     at android.os.Handler.handleCallback(Handler.java:751)

04-08 15:06:22.371 15856-15856/com.xyz W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)

04-08 15:06:22.371 15856-15856/com.xyz W/System.err:     at android.os.Looper.loop(Looper.java:154)

04-08 15:06:22.371 15856-15856/com.xyz W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:6682)

04-08 15:06:22.371 15856-15856/com.xyz W/System.err:     at java.lang.reflect.Method.invoke(Native Method)

04-08 15:06:22.371 15856-15856/com.xyz W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)

04-08 15:06:22.371 15856-15856/com.xyz W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)

04-08 15:06:22.372 15856-15856/com.xyz W/System.err: Caused by: java.lang.ClassCastException: android.app.Application cannot be cast to android.app.Activity

04-08 15:06:22.372 15856-15856/com.xyz W/System.err:     at com.tentwenty.notifyme.graph.suitlines.SuitLines.<init>(SuitLines.java:82)

04-08 15:06:22.373 15856-15856/com.xyz W/System.err:     at com.tentwenty.notifyme.graph.suitlines.SuitLines.<init>(SuitLines.java:0)

Please let me know what i am doing wrong. Thank you.

**Comment by whataa** [comment]
Sorry, there is no specific reason for this stack, but I recommend that you ensure that the classes declared in the xml are consistent with the classpath in the java src.
