### ISSUE TITLE
画图适配

### ISSUE THREAD

**Issue by BolexLiu** [whataa/SuitLines#4]
请教一个问题，您是如何处理画图适配屏幕的问题的呢？

**Comment by whataa** [comment]
画线范围是相对View区域的，不太理解你的问题

**Comment by BolexLiu** [comment]
比如我们自定义了一个VIew。要求适配不同的手机上展示等比例绘制画布上的图。 比如画一条线是长度是10。那么在画布中这个10的单位是用的什么来表示呢？ 再一个若使用控件时传入了dp作为单位，是否还要考虑到转换单位再绘制的问题。

**Comment by whataa** [comment]
图肯定是适配了的，你也可以参见源码。例如指定了可见点的数量，不论屏幕多大大小，始终是指定的数量，变化的是两个点之间的间距。另外，对外的接口的参数只有xy轴的文字大小的单位需要是sp，其余的不涉及dp或者sp，因此整体来说，不用担心适配问题。

**Comment by BolexLiu** [comment]
好的，感谢。照这样理解。是不是除了字体是用了sp，其余的都是px。也就是基于像素来确定单位的？

**Comment by whataa** [comment]
是的，不过我建议你可以以具体的某个方法为例咨询。

最后感谢你的提问。
